### ISSUE TITLE
Promise-based API?

### ISSUE THREAD

**Issue by dandv** [premasagar/poloniex.js#13]
Same question as on [@tylerfilla](https://github.com/tylerfilla/node-poloniex-unofficial/issues/25)'s library.

**Comment by ohjames** [comment]
Would personally rather see an Observable/rxjs API, promises are great for single async values but here we're dealing with streams of async values.

**Comment by premasagar** [comment]
It would definitely make sense to return a Promise from each async function, to allow calling with `async/await` and other benefits. I'd return a Promise if the last argument is not a function, as other libraries often do.

**Comment by ohjames** [comment]
With some of the WebSocket APIs you get a streaming response, for these observables would be better, promises should be used for all the other APIs. The poloniex 1 API misses too much data, we reverse engineered version two of their API and expose everything via promises and rxjs. Maybe I can open source that bit.

**Comment by ohjames** [comment]
Here's a site we made which compares version 1 and 2 of the API: http://dangler.chilon.net/compare

As you can see their official API falls way behind and lacks most ticks.

**Comment by dutu** [comment]
@ohjames module [poloniex-api-node](https://github.com/dutu/poloniex-api-node) is updated to use the new WebSocket API (v2)

**Comment by ohjames** [comment]
@dutu Cool I see you added it 3 days ago, nice work. Would be nice if you exposed the streaming responses as Observables but. FRP rocks ;)

**Comment by anders94** [comment]
Closing this as there hasn't been discussion in a while. Moving to promises is a great idea if someone wants to pose a PR.
