### ISSUE TITLE
Rate cannot be greater than 5%?

### ISSUE THREAD

**Issue by greenuns** [premasagar/poloniex.js#21]
Hello,
First of all thank you for all your work.

I'm trying to execute a margin buy order but I keep getting:
error: rate cannot be greater than 5%.
Below is the code I am using. 
```
poloniex.marginBuy('BTC', 'ETH', 0.107, 0.19626168, 2, function(err, data){
    if (err){
        console.log('ERROR', err);
        return;
    }
    console.log(data);
});
```
I'm guessing rate is the price? (0.107) 
With the same values I'm able to place a margin order on the website but not through the API.
Is there something I'm doing wrong?

thank you.

**Comment by MarcDev2** [comment]
The 5th parameter must be below 0.05

**Comment by anders94** [comment]
This is a limit Poloniex enforces. (not a limit within `poloniex.js`)
