### ISSUE TITLE
Calls behind a proxy

### ISSUE THREAD

**Issue by Naigel56** [premasagar/poloniex.js#24]
Hello, I can use this library with my home pc, but when I try from another pc where traffic should pass through a proxy I can't get it work. I set the environmental variables HTTP_PROXY and HTTPS_PROXY but I get this error

> Error: connect ECONNREFUSED 104.20.13.48:443
>     at Object.exports._errnoException (util.js:1020:11)
>     at exports._exceptionWithHostPort (util.js:1043:20)
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
> code: 'ECONNREFUSED',
> errno: 'ECONNREFUSED',
> syscall: 'connect',
> address: '104.20.13.48',
> port: 443 }

Any idea on how to properly set proxy?

**Comment by premasagar** [comment]
The library uses the `request` module, which does support proxies:
https://www.npmjs.com/package/request#proxies

The library does not pass on a `proxy` option to request (it could be made to), but request does support configuring the proxy settings via environment variables, e.g. set `HTTPS_PROXY` to the proxy:
https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

**Comment by anders94** [comment]
@Naigel56 Does this work for you?

**Comment by anders94** [comment]
Closing this as there has been no response in a while.
