### ISSUE TITLE
I forked

### ISSUE THREAD

**Issue by askmike** [premasagar/poloniex.js#33]
I've been a big fan of this lib, have used it to trade close to a billion USDT (total volume, [example project](https://forum.gekko.wizb.it/thread-56746.html)). I have also been using it in my open source trading framework called gekko. Thanks a ton!

However a few reasons have forced me to use a forked version of this lib for a while. Most notably 2 dependencies (cloudscraper & request) are in need to be kept up to date because of security concerns (sometimes regarding their own deps), for example see: https://github.com/codemanki/cloudscraper/pull/63 (that PR has been merged but the fix has yet to hit NPM). The sec concerns are no issue for what this lib is doing, but NPM loves to inform to all gekko users that some dependency has a security vulnerability (which does not inspire confidence).

As such I wrote a drop in replacement (except for constructor) that doesn't use either of these deps (I don't think we need bulky request when talking to one specific API), it doesn't use any deps outside of nonce. To keep things lean and lightweight, and because that way I don't have to update the request version once a month because of some edge case vulnerability.

Here it is:

- github: http://github.com/askmike/poloniex.js
- npm: https://www.npmjs.com/package/gekko-broker-poloniex

I'll keep it up to date for as long as Gekko supports poloniex.

----

If you are interested in merging this in let me know :)

**Comment by anders94** [comment]
Thanks for this. I've been working on cleaning up several other inconsistencies. I'd be interested in a PR if you have the time.

**Comment by premasagar** [comment]
There are just 2 dependencies of this package - `nonce` and `request` - which are both up-to-date and do not present security vulnerabilities, as reported by `npm audit`.

I'm closing this issue; please re-open if you see any issues again. Thanks.
